# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161125182411 on 2016-12-20 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('pub_date', models.DateTimeField(verbose_name='published date')),
                ('edit_date', models.DateTimeField(verbose_name='edited date')),
                ('author', models.CharField(max_length=256, verbose_name='author')),
            ],
        ),
    ]
