# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161125182411 on 2016-12-20 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20161220_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='edited date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='published date'),
        ),
    ]
