# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_myuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default=b'/user.png', upload_to=b'', verbose_name=b'avatar'),
        ),
    ]
