# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20170501_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.IntegerField(blank=True, verbose_name=b'phone'),
        ),
    ]
